package com.john.plus.bean;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import org.junit.Test;

import java.util.Date;

@TableName("emp")
public class Emp {

   @TableId("empno")
   private Integer empno;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column emp.ename
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   private String ename;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column emp.job
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   private String job;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column emp.mgr
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   private String mgr;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column emp.hiredate
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   private Date hiredate;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column emp.sal
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   private Double sal;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column emp.comm
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   private Double comm;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column emp.deptno
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   private String deptno;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column emp.empno
    *
    * @return the value of emp.empno
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public Integer getEmpno() {
      return empno;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column emp.empno
    *
    * @param empno the value for emp.empno
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public void setEmpno(Integer empno) {
      this.empno = empno;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column emp.ename
    *
    * @return the value of emp.ename
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public String getEname() {
      return ename;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column emp.ename
    *
    * @param ename the value for emp.ename
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public void setEname(String ename) {
      this.ename = ename;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column emp.job
    *
    * @return the value of emp.job
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public String getJob() {
      return job;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column emp.job
    *
    * @param job the value for emp.job
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public void setJob(String job) {
      this.job = job;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column emp.mgr
    *
    * @return the value of emp.mgr
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public String getMgr() {
      return mgr;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column emp.mgr
    *
    * @param mgr the value for emp.mgr
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public void setMgr(String mgr) {
      this.mgr = mgr;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column emp.hiredate
    *
    * @return the value of emp.hiredate
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public Date getHiredate() {
      return hiredate;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column emp.hiredate
    *
    * @param hiredate the value for emp.hiredate
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public void setHiredate(Date hiredate) {
      this.hiredate = hiredate;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column emp.sal
    *
    * @return the value of emp.sal
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public Double getSal() {
      return sal;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column emp.sal
    *
    * @param sal the value for emp.sal
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public void setSal(Double sal) {
      this.sal = sal;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column emp.comm
    *
    * @return the value of emp.comm
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public Double getComm() {
      return comm;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column emp.comm
    *
    * @param comm the value for emp.comm
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public void setComm(Double comm) {
      this.comm = comm;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column emp.deptno
    *
    * @return the value of emp.deptno
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public String getDeptno() {
      return deptno;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column emp.deptno
    *
    * @param deptno the value for emp.deptno
    *
    * @mbg.generated Wed Oct 20 18:23:29 CST 2021
    */
   public void setDeptno(String deptno) {
      this.deptno = deptno;
   }

   @Override
   public String toString() {
      return "Emp{" +
              "empno=" + empno +
              ", ename='" + ename + '\'' +
              ", job='" + job + '\'' +
              ", mgr='" + mgr + '\'' +
              ", hiredate=" + hiredate +
              ", sal=" + sal +
              ", comm=" + comm +
              ", deptno='" + deptno + '\'' +
              '}';
   }
}