package com.john.bean;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptno
     *
     * @mbg.generated Wed Oct 20 18:23:29 CST 2021
     */
    private Integer deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptname
     *
     * @mbg.generated Wed Oct 20 18:23:29 CST 2021
     */
    private String deptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dloc
     *
     * @mbg.generated Wed Oct 20 18:23:29 CST 2021
     */
    private String dloc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptno
     *
     * @return the value of dept.deptno
     *
     * @mbg.generated Wed Oct 20 18:23:29 CST 2021
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptno
     *
     * @param deptno the value for dept.deptno
     *
     * @mbg.generated Wed Oct 20 18:23:29 CST 2021
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptname
     *
     * @return the value of dept.deptname
     *
     * @mbg.generated Wed Oct 20 18:23:29 CST 2021
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptname
     *
     * @param deptname the value for dept.deptname
     *
     * @mbg.generated Wed Oct 20 18:23:29 CST 2021
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dloc
     *
     * @return the value of dept.dloc
     *
     * @mbg.generated Wed Oct 20 18:23:29 CST 2021
     */
    public String getDloc() {
        return dloc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dloc
     *
     * @param dloc the value for dept.dloc
     *
     * @mbg.generated Wed Oct 20 18:23:29 CST 2021
     */
    public void setDloc(String dloc) {
        this.dloc = dloc;
    }
}